# Generated by Django 2.2.1 on 2019-05-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGZ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.PositiveIntegerField(choices=[(0, 'Masculino'), (1, 'Femenino')], default=0),
        ),
    ]
