# Generated by Django 2.2.4 on 2019-08-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGZ', '0002_animal_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='type_of_donation',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'comida de gato'), (1, 'comida de perro'), (2, 'remedios'), (3, 'collar'), (4, 'otros')], default=0, null=True),
        ),
    ]
