# Generated by Django 2.2.1 on 2019-06-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGZ', '0002_auto_20190523_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAP',
            fields=[
                ('id_cap', models.AutoField(primary_key=True, serialize=False)),
                ('nameC', models.CharField(max_length=20)),
                ('last_nameC', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=120)),
            ],
        ),
    ]
