# Generated by Django 2.2.4 on 2019-08-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGZ', '0003_auto_20190822_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='temperamento',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
