# Generated by Django 2.2.1 on 2019-06-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGZ', '0003_cap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='date_founded',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Masculino'), (1, 'Femenino')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='place_founded',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='race',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
