# Generated by Django 2.2.4 on 2019-08-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGZ', '0004_animal_temperamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialM',
            fields=[
                ('id_HM', models.AutoField(primary_key=True, serialize=False)),
                ('enfermedad', models.CharField(blank=True, max_length=240, null=True)),
                ('fecha_h', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('estado', models.PositiveIntegerField(blank=True, choices=[(0, 'curado'), (1, 'no curado')], default=0, null=True)),
            ],
        ),
    ]
