# Generated by Django 2.2.4 on 2019-08-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FGZ', '0005_historialm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialm',
            old_name='fecha_h',
            new_name='fecha',
        ),
    ]
