# Generated by Django 2.2.4 on 2019-08-28 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FGZ', '0006_auto_20190828_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialm',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FGZ.Animal'),
        ),
    ]
