# Generated by Django 2.2.3 on 2019-07-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FGZ', '0007_auto_20190725_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monto',
            old_name='amount_to_enter',
            new_name='amount',
        ),
    ]
