# Generated by Django 2.2.4 on 2019-08-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGZ', '0008_donacion_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
