# Generated by Django 2.2.3 on 2019-07-29 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGZ', '0008_auto_20190726_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monto',
            name='amount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
