# Generated by Django 2.2.4 on 2019-09-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGZ', '0009_animal_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='historia',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
