# Generated by Django 2.2.3 on 2019-07-30 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGZ', '0009_auto_20190729_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monto',
            name='amount',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
