# Generated by Django 2.2.3 on 2019-08-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGZ', '0010_auto_20190730_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='cap',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cap',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='cap',
            name='age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cap',
            name='last_nameC',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cap',
            name='nameC',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
