# Generated by Django 2.2.3 on 2019-07-30 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FGZ', '0010_auto_20190730_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='cap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FGZ.CAP'),
        ),
    ]
