# Generated by Django 2.2.4 on 2019-10-24 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FGZ', '0011_auto_20191024_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cap',
            old_name='telefono',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='donacion',
            old_name='cantidad',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='historialm',
            old_name='fecha',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='historialm',
            old_name='enfermedad',
            new_name='illness',
        ),
        migrations.RenameField(
            model_name='historialm',
            old_name='estado',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='monto',
            old_name='tipo',
            new_name='type',
        ),
    ]
