# Generated by Django 2.2.3 on 2019-08-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGZ', '0011_auto_20190806_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id_donation', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=240, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('type_of_donation', models.PositiveIntegerField(blank=True, choices=[(0, 'gato'), (1, 'perro'), (2, 'ropa'), (3, 'otros')], default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cap',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
