# Generated by Django 2.2.4 on 2019-10-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGZ', '0012_auto_20191024_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='gender',
        ),
        migrations.AddField(
            model_name='animal',
            name='sex',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='historialm',
            name='state',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'cured'), (1, 'uncured')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monto',
            name='type',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Deposit'), (1, 'Expense')], default=0, null=True),
        ),
    ]
