# Generated by Django 2.2.3 on 2019-08-08 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FGZ', '0015_venue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
