# Generated by Django 2.2.3 on 2019-08-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FGZ', '0016_delete_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinaria',
            fields=[
                ('id_veterinaria', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='cap',
            name='last_nameC',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='cap',
            name='nameC',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='name'),
        ),
    ]
