# Generated by Django 2.2.4 on 2019-08-21 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FGZ', '0017_auto_20190813_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='veterinaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FGZ.Veterinaria'),
        ),
        migrations.AlterField(
            model_name='veterinaria',
            name='address',
            field=models.CharField(blank=True, max_length=270, null=True),
        ),
    ]
